//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("corrales_sistemaModel", "FK_USUARIOS_EMPRESA", "ordenes_empresas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NotificadorUniversal.Modelos.ordenes_empresas), "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NotificadorUniversal.Modelos.usuarios), true)]
[assembly: EdmRelationshipAttribute("corrales_sistemaModel", "FK_USUARIOS_JEFE", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NotificadorUniversal.Modelos.usuarios), "usuarios1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NotificadorUniversal.Modelos.usuarios), true)]
[assembly: EdmRelationshipAttribute("corrales_sistemaModel", "fk_programa", "programa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NotificadorUniversal.Modelos.programa), "notificaciones", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NotificadorUniversal.Modelos.notificaciones), true)]
[assembly: EdmRelationshipAttribute("corrales_sistemaModel", "fk_User", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NotificadorUniversal.Modelos.usuarios), "notificaciones", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NotificadorUniversal.Modelos.notificaciones), true)]

#endregion

namespace NotificadorUniversal.Modelos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class corrales_sistemaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto corrales_sistemaEntities usando la cadena de conexión encontrada en la sección 'corrales_sistemaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public corrales_sistemaEntities() : base("name=corrales_sistemaEntities", "corrales_sistemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto corrales_sistemaEntities.
        /// </summary>
        public corrales_sistemaEntities(string connectionString) : base(connectionString, "corrales_sistemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto corrales_sistemaEntities.
        /// </summary>
        public corrales_sistemaEntities(EntityConnection connection) : base(connection, "corrales_sistemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ordenes_empresas> ordenes_empresas
        {
            get
            {
                if ((_ordenes_empresas == null))
                {
                    _ordenes_empresas = base.CreateObjectSet<ordenes_empresas>("ordenes_empresas");
                }
                return _ordenes_empresas;
            }
        }
        private ObjectSet<ordenes_empresas> _ordenes_empresas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<programa> programa
        {
            get
            {
                if ((_programa == null))
                {
                    _programa = base.CreateObjectSet<programa>("programa");
                }
                return _programa;
            }
        }
        private ObjectSet<programa> _programa;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<notificaciones> notificaciones
        {
            get
            {
                if ((_notificaciones == null))
                {
                    _notificaciones = base.CreateObjectSet<notificaciones>("notificaciones");
                }
                return _notificaciones;
            }
        }
        private ObjectSet<notificaciones> _notificaciones;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ordenes_empresas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToordenes_empresas(ordenes_empresas ordenes_empresas)
        {
            base.AddObject("ordenes_empresas", ordenes_empresas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet programa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToprograma(programa programa)
        {
            base.AddObject("programa", programa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet notificaciones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTonotificaciones(notificaciones notificaciones)
        {
            base.AddObject("notificaciones", notificaciones);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_sistemaModel", Name="notificaciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class notificaciones : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto notificaciones.
        /// </summary>
        /// <param name="idnotificacion">Valor inicial de la propiedad idnotificacion.</param>
        /// <param name="idusuario">Valor inicial de la propiedad idusuario.</param>
        /// <param name="idsucursal">Valor inicial de la propiedad idsucursal.</param>
        /// <param name="notificacion">Valor inicial de la propiedad notificacion.</param>
        /// <param name="idprograma">Valor inicial de la propiedad idprograma.</param>
        /// <param name="msjtodos">Valor inicial de la propiedad msjtodos.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static notificaciones Createnotificaciones(global::System.Int32 idnotificacion, global::System.Int32 idusuario, global::System.Int32 idsucursal, global::System.String notificacion, global::System.Int32 idprograma, global::System.Int32 msjtodos, global::System.Int32 estatus)
        {
            notificaciones notificaciones = new notificaciones();
            notificaciones.idnotificacion = idnotificacion;
            notificaciones.idusuario = idusuario;
            notificaciones.idsucursal = idsucursal;
            notificaciones.notificacion = notificacion;
            notificaciones.idprograma = idprograma;
            notificaciones.msjtodos = msjtodos;
            notificaciones.estatus = estatus;
            return notificaciones;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idnotificacion
        {
            get
            {
                return _idnotificacion;
            }
            set
            {
                if (_idnotificacion != value)
                {
                    OnidnotificacionChanging(value);
                    ReportPropertyChanging("idnotificacion");
                    _idnotificacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idnotificacion");
                    OnidnotificacionChanged();
                }
            }
        }
        private global::System.Int32 _idnotificacion;
        partial void OnidnotificacionChanging(global::System.Int32 value);
        partial void OnidnotificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                OnidusuarioChanging(value);
                ReportPropertyChanging("idusuario");
                _idusuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idusuario");
                OnidusuarioChanged();
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idsucursal
        {
            get
            {
                return _idsucursal;
            }
            set
            {
                OnidsucursalChanging(value);
                ReportPropertyChanging("idsucursal");
                _idsucursal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idsucursal");
                OnidsucursalChanged();
            }
        }
        private global::System.Int32 _idsucursal;
        partial void OnidsucursalChanging(global::System.Int32 value);
        partial void OnidsucursalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String notificacion
        {
            get
            {
                return _notificacion;
            }
            set
            {
                OnnotificacionChanging(value);
                ReportPropertyChanging("notificacion");
                _notificacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("notificacion");
                OnnotificacionChanged();
            }
        }
        private global::System.String _notificacion;
        partial void OnnotificacionChanging(global::System.String value);
        partial void OnnotificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idprograma
        {
            get
            {
                return _idprograma;
            }
            set
            {
                OnidprogramaChanging(value);
                ReportPropertyChanging("idprograma");
                _idprograma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idprograma");
                OnidprogramaChanged();
            }
        }
        private global::System.Int32 _idprograma;
        partial void OnidprogramaChanging(global::System.Int32 value);
        partial void OnidprogramaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 msjtodos
        {
            get
            {
                return _msjtodos;
            }
            set
            {
                OnmsjtodosChanging(value);
                ReportPropertyChanging("msjtodos");
                _msjtodos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("msjtodos");
                OnmsjtodosChanged();
            }
        }
        private global::System.Int32 _msjtodos;
        partial void OnmsjtodosChanging(global::System.Int32 value);
        partial void OnmsjtodosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.Int32 _estatus;
        partial void OnestatusChanging(global::System.Int32 value);
        partial void OnestatusChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_sistemaModel", "fk_programa", "programa")]
        public programa programa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<programa>("corrales_sistemaModel.fk_programa", "programa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<programa>("corrales_sistemaModel.fk_programa", "programa").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<programa> programaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<programa>("corrales_sistemaModel.fk_programa", "programa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<programa>("corrales_sistemaModel.fk_programa", "programa", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_sistemaModel", "fk_User", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("corrales_sistemaModel.fk_User", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("corrales_sistemaModel.fk_User", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("corrales_sistemaModel.fk_User", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("corrales_sistemaModel.fk_User", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_sistemaModel", Name="ordenes_empresas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ordenes_empresas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ordenes_empresas.
        /// </summary>
        /// <param name="idempresa">Valor inicial de la propiedad idempresa.</param>
        /// <param name="nombrecorto">Valor inicial de la propiedad nombrecorto.</param>
        /// <param name="nombreempresa">Valor inicial de la propiedad nombreempresa.</param>
        /// <param name="calle">Valor inicial de la propiedad calle.</param>
        /// <param name="numero">Valor inicial de la propiedad numero.</param>
        /// <param name="colonia">Valor inicial de la propiedad colonia.</param>
        /// <param name="ciudad">Valor inicial de la propiedad ciudad.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="pais">Valor inicial de la propiedad pais.</param>
        /// <param name="rfc">Valor inicial de la propiedad rfc.</param>
        /// <param name="telefono">Valor inicial de la propiedad telefono.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="status">Valor inicial de la propiedad status.</param>
        public static ordenes_empresas Createordenes_empresas(global::System.Int32 idempresa, global::System.String nombrecorto, global::System.String nombreempresa, global::System.String calle, global::System.String numero, global::System.String colonia, global::System.String ciudad, global::System.String estado, global::System.String pais, global::System.String rfc, global::System.Int32 telefono, global::System.String email, global::System.Int32 status)
        {
            ordenes_empresas ordenes_empresas = new ordenes_empresas();
            ordenes_empresas.idempresa = idempresa;
            ordenes_empresas.nombrecorto = nombrecorto;
            ordenes_empresas.nombreempresa = nombreempresa;
            ordenes_empresas.calle = calle;
            ordenes_empresas.numero = numero;
            ordenes_empresas.colonia = colonia;
            ordenes_empresas.ciudad = ciudad;
            ordenes_empresas.estado = estado;
            ordenes_empresas.pais = pais;
            ordenes_empresas.rfc = rfc;
            ordenes_empresas.telefono = telefono;
            ordenes_empresas.email = email;
            ordenes_empresas.status = status;
            return ordenes_empresas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idempresa
        {
            get
            {
                return _idempresa;
            }
            set
            {
                if (_idempresa != value)
                {
                    OnidempresaChanging(value);
                    ReportPropertyChanging("idempresa");
                    _idempresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idempresa");
                    OnidempresaChanged();
                }
            }
        }
        private global::System.Int32 _idempresa;
        partial void OnidempresaChanging(global::System.Int32 value);
        partial void OnidempresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombrecorto
        {
            get
            {
                return _nombrecorto;
            }
            set
            {
                OnnombrecortoChanging(value);
                ReportPropertyChanging("nombrecorto");
                _nombrecorto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombrecorto");
                OnnombrecortoChanged();
            }
        }
        private global::System.String _nombrecorto;
        partial void OnnombrecortoChanging(global::System.String value);
        partial void OnnombrecortoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreempresa
        {
            get
            {
                return _nombreempresa;
            }
            set
            {
                OnnombreempresaChanging(value);
                ReportPropertyChanging("nombreempresa");
                _nombreempresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreempresa");
                OnnombreempresaChanged();
            }
        }
        private global::System.String _nombreempresa;
        partial void OnnombreempresaChanging(global::System.String value);
        partial void OnnombreempresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String calle
        {
            get
            {
                return _calle;
            }
            set
            {
                OncalleChanging(value);
                ReportPropertyChanging("calle");
                _calle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("calle");
                OncalleChanged();
            }
        }
        private global::System.String _calle;
        partial void OncalleChanging(global::System.String value);
        partial void OncalleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.String _numero;
        partial void OnnumeroChanging(global::System.String value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String colonia
        {
            get
            {
                return _colonia;
            }
            set
            {
                OncoloniaChanging(value);
                ReportPropertyChanging("colonia");
                _colonia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("colonia");
                OncoloniaChanged();
            }
        }
        private global::System.String _colonia;
        partial void OncoloniaChanging(global::System.String value);
        partial void OncoloniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ciudad
        {
            get
            {
                return _ciudad;
            }
            set
            {
                OnciudadChanging(value);
                ReportPropertyChanging("ciudad");
                _ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ciudad");
                OnciudadChanged();
            }
        }
        private global::System.String _ciudad;
        partial void OnciudadChanging(global::System.String value);
        partial void OnciudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pais
        {
            get
            {
                return _pais;
            }
            set
            {
                OnpaisChanging(value);
                ReportPropertyChanging("pais");
                _pais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pais");
                OnpaisChanged();
            }
        }
        private global::System.String _pais;
        partial void OnpaisChanging(global::System.String value);
        partial void OnpaisChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cp
        {
            get
            {
                return _cp;
            }
            set
            {
                OncpChanging(value);
                ReportPropertyChanging("cp");
                _cp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cp");
                OncpChanged();
            }
        }
        private Nullable<global::System.Int32> _cp;
        partial void OncpChanging(Nullable<global::System.Int32> value);
        partial void OncpChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rfc
        {
            get
            {
                return _rfc;
            }
            set
            {
                OnrfcChanging(value);
                ReportPropertyChanging("rfc");
                _rfc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rfc");
                OnrfcChanged();
            }
        }
        private global::System.String _rfc;
        partial void OnrfcChanging(global::System.String value);
        partial void OnrfcChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.Int32 _telefono;
        partial void OntelefonoChanging(global::System.Int32 value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String direccionlocal
        {
            get
            {
                return _direccionlocal;
            }
            set
            {
                OndireccionlocalChanging(value);
                ReportPropertyChanging("direccionlocal");
                _direccionlocal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccionlocal");
                OndireccionlocalChanged();
            }
        }
        private global::System.String _direccionlocal;
        partial void OndireccionlocalChanging(global::System.String value);
        partial void OndireccionlocalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String direccionexterna
        {
            get
            {
                return _direccionexterna;
            }
            set
            {
                OndireccionexternaChanging(value);
                ReportPropertyChanging("direccionexterna");
                _direccionexterna = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccionexterna");
                OndireccionexternaChanged();
            }
        }
        private global::System.String _direccionexterna;
        partial void OndireccionexternaChanging(global::System.String value);
        partial void OndireccionexternaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_sistemaModel", "FK_USUARIOS_EMPRESA", "usuarios")]
        public EntityCollection<usuarios> usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuarios>("corrales_sistemaModel.FK_USUARIOS_EMPRESA", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuarios>("corrales_sistemaModel.FK_USUARIOS_EMPRESA", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_sistemaModel", Name="programa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class programa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto programa.
        /// </summary>
        /// <param name="idprograma">Valor inicial de la propiedad idprograma.</param>
        public static programa Createprograma(global::System.Int32 idprograma)
        {
            programa programa = new programa();
            programa.idprograma = idprograma;
            return programa;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idprograma
        {
            get
            {
                return _idprograma;
            }
            set
            {
                if (_idprograma != value)
                {
                    OnidprogramaChanging(value);
                    ReportPropertyChanging("idprograma");
                    _idprograma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idprograma");
                    OnidprogramaChanged();
                }
            }
        }
        private global::System.Int32 _idprograma;
        partial void OnidprogramaChanging(global::System.Int32 value);
        partial void OnidprogramaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String carpeta
        {
            get
            {
                return _carpeta;
            }
            set
            {
                OncarpetaChanging(value);
                ReportPropertyChanging("carpeta");
                _carpeta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("carpeta");
                OncarpetaChanged();
            }
        }
        private global::System.String _carpeta;
        partial void OncarpetaChanging(global::System.String value);
        partial void OncarpetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icono
        {
            get
            {
                return _icono;
            }
            set
            {
                OniconoChanging(value);
                ReportPropertyChanging("icono");
                _icono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icono");
                OniconoChanged();
            }
        }
        private global::System.String _icono;
        partial void OniconoChanging(global::System.String value);
        partial void OniconoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ensucursal
        {
            get
            {
                return _ensucursal;
            }
            set
            {
                OnensucursalChanging(value);
                ReportPropertyChanging("ensucursal");
                _ensucursal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ensucursal");
                OnensucursalChanged();
            }
        }
        private Nullable<global::System.Int32> _ensucursal;
        partial void OnensucursalChanging(Nullable<global::System.Int32> value);
        partial void OnensucursalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Int32> _status;
        partial void OnstatusChanging(Nullable<global::System.Int32> value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String liganotificacion
        {
            get
            {
                return _liganotificacion;
            }
            set
            {
                OnliganotificacionChanging(value);
                ReportPropertyChanging("liganotificacion");
                _liganotificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("liganotificacion");
                OnliganotificacionChanged();
            }
        }
        private global::System.String _liganotificacion;
        partial void OnliganotificacionChanging(global::System.String value);
        partial void OnliganotificacionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_sistemaModel", "fk_programa", "notificaciones")]
        public EntityCollection<notificaciones> notificaciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<notificaciones>("corrales_sistemaModel.fk_programa", "notificaciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<notificaciones>("corrales_sistemaModel.fk_programa", "notificaciones", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_sistemaModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="idusuario">Valor inicial de la propiedad idusuario.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="fechanacimiento">Valor inicial de la propiedad fechanacimiento.</param>
        /// <param name="puesto">Valor inicial de la propiedad puesto.</param>
        /// <param name="jefeinmediato">Valor inicial de la propiedad jefeinmediato.</param>
        /// <param name="correobase">Valor inicial de la propiedad correobase.</param>
        /// <param name="fecharegistro">Valor inicial de la propiedad fecharegistro.</param>
        /// <param name="acceso">Valor inicial de la propiedad acceso.</param>
        /// <param name="idempresa">Valor inicial de la propiedad idempresa.</param>
        /// <param name="status">Valor inicial de la propiedad status.</param>
        /// <param name="fechaultimoacceso">Valor inicial de la propiedad fechaultimoacceso.</param>
        public static usuarios Createusuarios(global::System.Int32 idusuario, global::System.String usuario, global::System.String clave, global::System.String nombre, global::System.DateTime fechanacimiento, global::System.String puesto, global::System.Int32 jefeinmediato, global::System.String correobase, global::System.DateTime fecharegistro, global::System.Int32 acceso, global::System.Int32 idempresa, global::System.Int32 status, global::System.DateTime fechaultimoacceso)
        {
            usuarios usuarios = new usuarios();
            usuarios.idusuario = idusuario;
            usuarios.usuario = usuario;
            usuarios.clave = clave;
            usuarios.nombre = nombre;
            usuarios.fechanacimiento = fechanacimiento;
            usuarios.puesto = puesto;
            usuarios.jefeinmediato = jefeinmediato;
            usuarios.correobase = correobase;
            usuarios.fecharegistro = fecharegistro;
            usuarios.acceso = acceso;
            usuarios.idempresa = idempresa;
            usuarios.status = status;
            usuarios.fechaultimoacceso = fechaultimoacceso;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechanacimiento
        {
            get
            {
                return _fechanacimiento;
            }
            set
            {
                OnfechanacimientoChanging(value);
                ReportPropertyChanging("fechanacimiento");
                _fechanacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechanacimiento");
                OnfechanacimientoChanged();
            }
        }
        private global::System.DateTime _fechanacimiento;
        partial void OnfechanacimientoChanging(global::System.DateTime value);
        partial void OnfechanacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String puesto
        {
            get
            {
                return _puesto;
            }
            set
            {
                OnpuestoChanging(value);
                ReportPropertyChanging("puesto");
                _puesto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("puesto");
                OnpuestoChanged();
            }
        }
        private global::System.String _puesto;
        partial void OnpuestoChanging(global::System.String value);
        partial void OnpuestoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 jefeinmediato
        {
            get
            {
                return _jefeinmediato;
            }
            set
            {
                OnjefeinmediatoChanging(value);
                ReportPropertyChanging("jefeinmediato");
                _jefeinmediato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jefeinmediato");
                OnjefeinmediatoChanged();
            }
        }
        private global::System.Int32 _jefeinmediato;
        partial void OnjefeinmediatoChanging(global::System.Int32 value);
        partial void OnjefeinmediatoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String correobase
        {
            get
            {
                return _correobase;
            }
            set
            {
                OncorreobaseChanging(value);
                ReportPropertyChanging("correobase");
                _correobase = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("correobase");
                OncorreobaseChanged();
            }
        }
        private global::System.String _correobase;
        partial void OncorreobaseChanging(global::System.String value);
        partial void OncorreobaseChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecharegistro
        {
            get
            {
                return _fecharegistro;
            }
            set
            {
                OnfecharegistroChanging(value);
                ReportPropertyChanging("fecharegistro");
                _fecharegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecharegistro");
                OnfecharegistroChanged();
            }
        }
        private global::System.DateTime _fecharegistro;
        partial void OnfecharegistroChanging(global::System.DateTime value);
        partial void OnfecharegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 acceso
        {
            get
            {
                return _acceso;
            }
            set
            {
                OnaccesoChanging(value);
                ReportPropertyChanging("acceso");
                _acceso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("acceso");
                OnaccesoChanged();
            }
        }
        private global::System.Int32 _acceso;
        partial void OnaccesoChanging(global::System.Int32 value);
        partial void OnaccesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idempresa
        {
            get
            {
                return _idempresa;
            }
            set
            {
                OnidempresaChanging(value);
                ReportPropertyChanging("idempresa");
                _idempresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idempresa");
                OnidempresaChanged();
            }
        }
        private global::System.Int32 _idempresa;
        partial void OnidempresaChanging(global::System.Int32 value);
        partial void OnidempresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaultimoacceso
        {
            get
            {
                return _fechaultimoacceso;
            }
            set
            {
                OnfechaultimoaccesoChanging(value);
                ReportPropertyChanging("fechaultimoacceso");
                _fechaultimoacceso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaultimoacceso");
                OnfechaultimoaccesoChanged();
            }
        }
        private global::System.DateTime _fechaultimoacceso;
        partial void OnfechaultimoaccesoChanging(global::System.DateTime value);
        partial void OnfechaultimoaccesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> jefe
        {
            get
            {
                return _jefe;
            }
            set
            {
                OnjefeChanging(value);
                ReportPropertyChanging("jefe");
                _jefe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jefe");
                OnjefeChanged();
            }
        }
        private Nullable<global::System.Int32> _jefe;
        partial void OnjefeChanging(Nullable<global::System.Int32> value);
        partial void OnjefeChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_sistemaModel", "FK_USUARIOS_EMPRESA", "ordenes_empresas")]
        public ordenes_empresas ordenes_empresas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ordenes_empresas>("corrales_sistemaModel.FK_USUARIOS_EMPRESA", "ordenes_empresas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ordenes_empresas>("corrales_sistemaModel.FK_USUARIOS_EMPRESA", "ordenes_empresas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ordenes_empresas> ordenes_empresasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ordenes_empresas>("corrales_sistemaModel.FK_USUARIOS_EMPRESA", "ordenes_empresas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ordenes_empresas>("corrales_sistemaModel.FK_USUARIOS_EMPRESA", "ordenes_empresas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_sistemaModel", "FK_USUARIOS_JEFE", "usuarios1")]
        public EntityCollection<usuarios> usuarios1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuarios>("corrales_sistemaModel.FK_USUARIOS_JEFE", "usuarios1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuarios>("corrales_sistemaModel.FK_USUARIOS_JEFE", "usuarios1", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_sistemaModel", "FK_USUARIOS_JEFE", "usuarios")]
        public usuarios usuarios2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("corrales_sistemaModel.FK_USUARIOS_JEFE", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("corrales_sistemaModel.FK_USUARIOS_JEFE", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuarios2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("corrales_sistemaModel.FK_USUARIOS_JEFE", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("corrales_sistemaModel.FK_USUARIOS_JEFE", "usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_sistemaModel", "fk_User", "notificaciones")]
        public EntityCollection<notificaciones> notificaciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<notificaciones>("corrales_sistemaModel.fk_User", "notificaciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<notificaciones>("corrales_sistemaModel.fk_User", "notificaciones", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
